const mongoose = require("mongoose");

const listingSchema = new mongoose.Schema(
  {
    sellerId: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    title: { type: String, required: true },
    subtitle: { type: String },
    description: { type: String },
    categoryId: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    category: { type: String, default: "Other" },
    itemSpecifics: {
      brand: { type: String, default: "" },
      model: { type: String, default: "" },
      size: { type: String, default: "" },
      color: { type: String, default: "" },
      department: { type: String, default: "" },
      storageCapacity: { type: String, default: "" },
      network: { type: String, default: "" },
      ram: { type: String, default: "" },
      screenSize: { type: String, default: "" },
    },
    condition: {
      type: String,
      enum: ["new", "like_new", "good", "acceptable"],
      default: "new",
    },
    images: [{ type: String }],
    pricing: {
      currency: { type: String, default: "VND" },
      fixedPrice: { type: Number },
      format: { type: String, enum: ["auction", "fixed"], default: "fixed" },
      startingBid: { type: Number },
      buyItNowPrice: { type: Number },
      reservePrice: { type: Number },
      auctionDuration: { type: String },
      immediatePayment: { type: Boolean, default: false },
      currentBid: { type: Number, default: 0 },
      bidCount: { type: Number, default: 0 },
      auctionEndsAt: { type: Date },
    },
    totalQuantity: { type: Number, default: 1 },
    status: {
      type: String,
      enum: ["active", "inactive", "sold"],
      default: "active",
    },
    isFeatured: { type: Boolean, default: false },
    isPromoted: { type: Boolean, default: false },
    stats: {
      views: { type: Number, default: 0 },
      watchers: { type: Number, default: 0 },
      soldQuantity: { type: Number, default: 0 },
    },
    reviews: {
      averageRating: { type: Number, default: 0 },
      reviewCount: { type: Number, default: 0 },
    },
    shippingPolicyId: { type: mongoose.Schema.Types.ObjectId },
    shippingMethod: { type: String, default: "Standard shipping" },
    shippingCost: { type: Number, default: 0 },
    handlingTime: { type: String, default: "1 business day" },
    shippingFrom: { type: String, default: "" },
    itemOrigin: { type: String, default: "Vietnam" },
    shippingCostType: { type: String, default: "flat" },
    packageWeightLbs: { type: Number },
    packageWeightOz: { type: Number },
    packageLength: { type: Number },
    packageWidth: { type: Number },
    packageHeight: { type: Number },
    scheduled: { type: Boolean, default: false },
    returnPolicy: {
      acceptsReturns: { type: Boolean, default: false },
      window: { type: String, default: "No returns" },
      shippingPaidBy: { type: String, default: "Buyer" },
    },
    returnPolicyId: { type: mongoose.Schema.Types.ObjectId },
    paymentPolicyId: { type: mongoose.Schema.Types.ObjectId },
  },
  { timestamps: true },
);

module.exports = mongoose.model("Listing", listingSchema);
